#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Bindings
set -o vi
bindkey 'jk' vi-cmd-mode
bindkey "^R" history-incremental-search-backward

# Aliases
# LS_STRING="ls --ignore='lost+found' --color=auto"
# alias ls="$LS_STRING"
# alias sl="$LS_STRING"
alias dev='export NODE_ENV=development; echo "\$NODE_ENV=development"'
alias prod='export NODE_ENV=production; echo "\$NODE_ENV=production"'
alias vi='vim'
alias tmu='tmux'
alias gp='git push'
alias rm='nocorrect rm'
alias startx='cowsay "you mean xinit?"'
alias gpg="/usr/bin/gpg2"
alias git="hub"
alias python="python3"


[[ -s "/home/slee2/.gvm/scripts/gvm" ]] && source "/home/slee2/.gvm/scripts/gvm"

# set overwrite of files during piping
setopt CLOBBER
unsetopt AUTO_CD

# source z
. $HOME/.bin/z.sh
