# if [[ -n "$TERM_TRANS_TO" ]]; then
#   transset-df -a "$TERM_TRANS_TO">/dev/null
# else
#   [[ "$TERM" == "rxvt-unicode-256color" ]] && transset-df -a 0.9 >/dev/null
# fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi






# Bindings
set -o vi
bindkey 'jk' vi-cmd-mode
bindkey "^R" history-incremental-search-backward

# Aliases
# LS_STRING="ls --ignore='lost+found' --color=auto"
# alias ls="$LS_STRING"
# alias sl="$LS_STRING"
#alias dev='export NODE_ENV=development; echo "\$NODE_ENV=development"'
#alias prod='export NODE_ENV=production; echo "\$NODE_ENV=production"'
alias vi='nvim'
alias vim='nvim'
alias gp='git push'
alias rm='nocorrect rm'
#alias gpg="/usr/bin/gpg2"
alias git="hub"
alias ns="nix-shell --run"
alias nse="nix-shell --run emacs &"

export SC_JACK_DEFAULT_INPUTS="system:capture_1,system:capture_2"
export SC_JACK_DEFAULT_OUTPUTS="system:playback_1,system:playback_2"

alias scsynth="scsynth -u 57110"

[[ -s "/home/slee2/.gvm/scripts/gvm" ]] && source "/home/slee2/.gvm/scripts/gvm"

# set overwrite of files during piping
setopt CLOBBER
unsetopt AUTO_CD

# source z
. $HOME/.bin/z.sh



echo "    most frecent directories:\n"
z | tail -n 8
echo
